accelerate launch sd_finetuner_huggingface.py \
--pretrained_model_name_or_path="CompVis/stable-diffusion-v1-1" \
--use_ema \
--resolution=256 \
--center_crop \
--random_flip \
--train_batch_size=1 \
--gradient_accumulation_steps=4 \
--gradient_checkpointing \
--mixed_precision="fp16" \
--max_train_steps=5000 \
--learning_rate=1e-05 \
--max_grad_norm=1 \
--lr_scheduler="constant" \
--lr_warmup_steps=0 \
--output_dir="fashion_out_trial_2" \
--train_data_dir="./fashion_data" \
--caption_column="caption"